CREATE TABLE BILLUREG(USERID INT NOT NULL PRIMARY KEY,USERNAME VARCHAR(30),PASSWORD VARCHAR(30),REPASSWORD VARCHAR(30),EMAILID VARCHAR(20),MOBILENO NUMBER(10),AROLE CHAR(1));;
DROP TABLE BILLPRODUCT_DETAILS;

INSERT INTO BILLUREG VALUES(1,'Admin','Ese@123','Ese@123','eda@gmail.com',9874563210);
SELECT * FROM BILLUREG;

CREATE TABLE BILLCOM_DETAILS(COMID INT NOT NULL PRIMARY KEY,COMNAME VARCHAR(30),  VARCHAR(40),CRDATE VARCHAR(15));
SELECT * FROM BILLCOM_DETAILS;

CREATE TABLE BILLINVOICE_DETAILS(COMID_FK INT NOT NULL REFERENCES BILLCOM_DETAILS,INVID INT NOT NULL PRIMARY KEY,INVNO NUMBER(5),INVDATE VARCHAR(15),SERIAL NUMBER(5),INVLOCATION CHAR(30),CHALANNO NUMBER(5));
SELECT * FROM BILLINVOICE_DETAILS;


CREATE TABLE BILLPRODUCT_DETAILS(COMID_FK INT NOT NULL REFERENCES BILLCOM_DETAILS,INVNO_FK INT NOT NULL REFERENCES BILLINVOICE_DETAILS,PRID INT NOT NULL PRIMARY KEY ,PRCRDATE VARCHAR(20),PRNAME VARCHAR(20),PRQTY NUMBER(5),PRRATE NUMBER(6),PRAMOUNT NUMBER(10));
SELECT * FROM BILLPRODUCT_DETAILS;

CREATE TABLE EBILL(BILLNO INT NOT NULL PRIMARY KEY,BILLDATE VARCHAR(15));
SELECT * FROM EBILL;
DELETE FROM EBILL WHERE BILLNO=4;
UPDATE BILLUREG SET AROLE='Y' where userid=4;
commit;
SELECT AROLE FROM BILLUREG WHERE USERNAME='Dinesh';
INSERT INTO INVOICE VALUES(1,1,1,to_date('24-03-2021','dd/MM/yyyy'),1,'erode',1);
SELECT * FROM BILLPRODUCT_DETAILS ORDER BY COMID_FK;

SELECT COMID,COMNAME,COMADDR FROM BILLCOM_DETAILS  WHERE CRDATE BETWEEN '22-03-2021' AND '26-03-2021' ORDER BY COMID;

SELECT COMID,COMNAME,COMADDR FROM BILLCOM_DETAILS WHERE extract(month from to_date(CRDATE,'dd-MM-yyyy')) = '03' ORDER BY COMID;

SELECT * FROM billimage